name: nazhe-agentv1-image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
      - name: pull repo
        uses: actions/checkout@v3
        
      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: build images and push to ghcr.io
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nezha-agent:v1
  
