name: example-01
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  my-job:
    name: 构建镜像并上传
    runs-on: ubuntu-latest
    steps:
      - name: 安装包依赖
        run: |
          apt update && apt install -y curl wget
      - name: 展示docker版本
        run: |
          docker -version




      
